# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MergeFilesAndZipDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MergeFilesAndZipDialog(object):
    def setupUi(self, MergeFilesAndZipDialog):
        MergeFilesAndZipDialog.setObjectName("MergeFilesAndZipDialog")
        MergeFilesAndZipDialog.resize(548, 305)
        self.gridLayoutWidget = QtWidgets.QWidget(MergeFilesAndZipDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 35))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.fileRadio.setChecked(True)
        self.fileRadio.setObjectName("fileRadio")
        self.horizontalLayout.addWidget(self.fileRadio)
        self.dirRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.dirRadio.setObjectName("dirRadio")
        self.horizontalLayout.addWidget(self.dirRadio)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.originBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originBtn.sizePolicy().hasHeightForWidth())
        self.originBtn.setSizePolicy(sizePolicy)
        self.originBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.originBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.originBtn.setSizeIncrement(QtCore.QSize(0, 0))
        self.originBtn.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.originBtn.setFont(font)
        self.originBtn.setAutoDefault(False)
        self.originBtn.setFlat(False)
        self.originBtn.setObjectName("originBtn")
        self.gridLayout.addWidget(self.originBtn, 0, 2, 1, 1)
        self.confirmBtn = QtWidgets.QPushButton(MergeFilesAndZipDialog)
        self.confirmBtn.setGeometry(QtCore.QRect(440, 270, 91, 32))
        self.confirmBtn.setObjectName("confirmBtn")
        self.cancelBtn = QtWidgets.QPushButton(MergeFilesAndZipDialog)
        self.cancelBtn.setGeometry(QtCore.QRect(350, 270, 91, 32))
        self.cancelBtn.setObjectName("cancelBtn")
        self.listView = QtWidgets.QListView(MergeFilesAndZipDialog)
        self.listView.setGeometry(QtCore.QRect(20, 80, 511, 151))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(MergeFilesAndZipDialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(MergeFilesAndZipDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 230, 511, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.zipEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.zipEdit.setObjectName("zipEdit")
        self.horizontalLayout_2.addWidget(self.zipEdit)
        self.zipBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.zipBtn.setObjectName("zipBtn")
        self.horizontalLayout_2.addWidget(self.zipBtn)

        self.retranslateUi(MergeFilesAndZipDialog)
        QtCore.QMetaObject.connectSlotsByName(MergeFilesAndZipDialog)

    def retranslateUi(self, MergeFilesAndZipDialog):
        _translate = QtCore.QCoreApplication.translate
        MergeFilesAndZipDialog.setWindowTitle(_translate("MergeFilesAndZipDialog", "Dialog"))
        self.fileRadio.setText(_translate("MergeFilesAndZipDialog", "文件"))
        self.dirRadio.setText(_translate("MergeFilesAndZipDialog", "文件夹"))
        self.label_2.setText(_translate("MergeFilesAndZipDialog", "文件类型"))
        self.originBtn.setText(_translate("MergeFilesAndZipDialog", "添加"))
        self.confirmBtn.setText(_translate("MergeFilesAndZipDialog", "确认"))
        self.cancelBtn.setText(_translate("MergeFilesAndZipDialog", "取消"))
        self.label.setText(_translate("MergeFilesAndZipDialog", "已选文件"))
        self.label_4.setText(_translate("MergeFilesAndZipDialog", "压缩到文件"))
        self.zipBtn.setText(_translate("MergeFilesAndZipDialog", "选择"))

