# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExecuteItemWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExecuteItemWidget(object):
    def setupUi(self, ExecuteItemWidget):
        ExecuteItemWidget.setObjectName("ExecuteItemWidget")
        ExecuteItemWidget.resize(395, 116)
        self.gridLayout_2 = QtWidgets.QGridLayout(ExecuteItemWidget)
        self.gridLayout_2.setContentsMargins(6, 2, 6, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.detailLabel = QtWidgets.QLabel(ExecuteItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailLabel.sizePolicy().hasHeightForWidth())
        self.detailLabel.setSizePolicy(sizePolicy)
        self.detailLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.detailLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.detailLabel.setFont(font)
        self.detailLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.detailLabel.setWordWrap(True)
        self.detailLabel.setIndent(0)
        self.detailLabel.setObjectName("detailLabel")
        self.gridLayout.addWidget(self.detailLabel, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nameLabel = QtWidgets.QLabel(ExecuteItemWidget)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.nameLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setWordWrap(False)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_4.addWidget(self.nameLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.editBtn = QtWidgets.QPushButton(ExecuteItemWidget)
        self.editBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_5.addWidget(self.editBtn)
        self.moveDownBtn = QtWidgets.QPushButton(ExecuteItemWidget)
        self.moveDownBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.moveDownBtn.setFont(font)
        self.moveDownBtn.setObjectName("moveDownBtn")
        self.horizontalLayout_5.addWidget(self.moveDownBtn)
        self.moveUpBtn = QtWidgets.QPushButton(ExecuteItemWidget)
        self.moveUpBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.moveUpBtn.setFont(font)
        self.moveUpBtn.setObjectName("moveUpBtn")
        self.horizontalLayout_5.addWidget(self.moveUpBtn)
        self.removeBtn = QtWidgets.QPushButton(ExecuteItemWidget)
        self.removeBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.removeBtn.setFont(font)
        self.removeBtn.setObjectName("removeBtn")
        self.horizontalLayout_5.addWidget(self.removeBtn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ExecuteItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ExecuteItemWidget)

    def retranslateUi(self, ExecuteItemWidget):
        _translate = QtCore.QCoreApplication.translate
        ExecuteItemWidget.setWindowTitle(_translate("ExecuteItemWidget", "Form"))
        self.detailLabel.setText(_translate("ExecuteItemWidget", "TextLabel"))
        self.nameLabel.setText(_translate("ExecuteItemWidget", "TextLabel"))
        self.editBtn.setText(_translate("ExecuteItemWidget", "编辑"))
        self.moveDownBtn.setText(_translate("ExecuteItemWidget", "下移"))
        self.moveUpBtn.setText(_translate("ExecuteItemWidget", "上移"))
        self.removeBtn.setText(_translate("ExecuteItemWidget", "移除"))

